env:
  - TRAVIS=true NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly

cache:
  directories:
    - node_modules

sudo: false
language: node_js
node_js:
  - "7"
script:
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
